### ISSUE TITLE
Sentença ambígua que não é ambígua

### ISSUE THREAD

**Issue by danilofragadantas** [lottec-ufpb/paratodxs#6]
Na linha 1168 do arquivo forallx-yyc-tfl.tex tem o seguinte exemplo de "sentença ambígua": Haskell é observador de pássaros e gosta de observar grous.  Os alunos devem dar uma chave de simbolização e simbolizar as diferentes leituras dessa sentença. 

Não encontrei a ambiguidade na tradução para o português. No original, em inglês, talvez haja uma ambiguidade lexical, já que "crane" é tanto "grua" (um guindaste) quanto "grou" (um pássaro).

Sugiro modificar o exemplo para utilizar uma palavra que seja ambígua em português, como "banco" ou algo do tipo.

**Comment by OliveiraHermogenes** [comment]
Estou de acordo. O que acha @diegofernandess ?

Abri #7 com uma proposta. Sintam-se livres para comentar e/ou adaptar.

**Comment by diegofernandess** [comment]
Sim, de acordo. Muito provavelmente mais um erro proveniente de tradução automática...

**Comment by diegofernandess** [comment]
Sim, de acordo. Muito provavelmente mais um erro proveniente de tradução automática...

**Comment by diegofernandess** [comment]
Sim, de acordo. Muito provavelmente mais um erro proveniente de tradução automática...
